# Begin CLS active localization fragment on rockfish

# This section will contain things like arrays for file systems with
# pathnames, so that the main parts of the code can refer to
# TARGET_FS[3] or whatever and have that be a valid path

# this is largely empty initially on rockfish because rockfish has
# statically defined ``$DATA'' which points to the scratch space

FPD_SYSTEM="rockfish"

# end CLS active job fragment
